### ISSUE TITLE
npm ERR! 404 Not Found

### ISSUE THREAD

**Issue by Molnfront** [Enkel-Digital/firebase-authentication#1]
Hi! I just tried your plugin and got this error:

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@enkeldigital%2ffirebase-authentication - Not found
npm ERR! 404 
npm ERR! 404  '@enkeldigital/firebase-authentication@latest' is not in the npm registry.

**Comment by Jaimeloeuf** [comment]
Hey! Can you describe how you got the error?

Im guessing it is an installation issue? Could you try installing with the following steps?

```shell
npm install @enkeldigital/firebase-authentication
npm install create-express-auth-middleware
```

**Comment by Jaimeloeuf** [comment]
@Molnfront all good?

**Comment by Molnfront** [comment]
Hi, I used your other npm package and that worked without a problem! --Sent from Yandex.Mail for mobile20.03.2022, 16:41, "Jaime" ***@***.***>:
@Molnfront all good?

**Comment by Jaimeloeuf** [comment]
@Molnfront good to hear! Do look out for a new update soon as that package will also be updated soon.

Am trying to consolidate all the packages so that it is easier to use in the future. The primary reason for the update is to support other authentication services other than firebase, such as Auth0 and Okta, while using the same library and same API!
